apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    app: nginx
    learning: rc
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: po-nginx
      labels:
        app: nginx
        learning: po
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
