apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
    learning: external-ip-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        learning: external-ip-service
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    learning: external-ip-service
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
---

apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip-service
  labels:
    app: nginx
    learning: external-ip-service
subsets:
  - addresses:
    - ip: 123.0.0.1
    ports:
    - port: 80
