apiVersion: v1
kind: Pod
metadata:
  name: nginx-port
  labels:
    app: nginx-port
    learning: pod
spec:
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
