apiVersion: v1
kind: Pod
metadata:
  name: pod-image-pull-policy
  labels:
    app: nginx
    learning: pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: Never
      # imagePullPolicy options are Never, IfNotPresent and Always
  restartPolicy: Never
