apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-container-port
  labels:
    app: nginx
    profile: test
    learning: pod
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
  restartPolicy: Never
